"""empty message

Revision ID: 54507d26e4a0
Revises: 5bf16a52867f
Create Date: 2022-11-17 17:35:03.406760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54507d26e4a0'
down_revision = '5bf16a52867f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.String(length=40), nullable=True))
    op.add_column('users', sa.Column('about', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('profile_visits', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('deactivated', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('profile_pic', sa.String(), nullable=True))
    op.add_column('users', sa.Column('finished_signup', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'finished_signup')
    op.drop_column('users', 'profile_pic')
    op.drop_column('users', 'deactivated')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'profile_visits')
    op.drop_column('users', 'age')
    op.drop_column('users', 'website')
    op.drop_column('users', 'about')
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###