pronouns = [
	"ey/em",
	"he/him",
	"ne/nem",
	"she/her",
	"they/them",
	"ve/ver",
	"xe/xem",
	"xie/xem",
	"ze/zir"
]

languages = [
	"Afrikaans",
	"Bahasa Indonesia",
	"Bahasa Malaysia",
	"Čeština",
	"Dansk",
	"Deutsch",
	"English (Australia)",
	"English (India)",
	"English (UK)",
	"English (US)",
	"Español (Américas)",
	"Español (Argentina)",
	"Español (España)",
	"Español (México)",
	"Français",
	"Hrvatski",
	"Italiano",
	"Magyar",
	"Nederlands",
	"Norsk bokmål",
	"Polski",
	"Português (Brasil)",
	"Português (Europeu)",
	"Română",
	"Slovenčina",
	"Suomi",
	"Svenska",
	"Tagalog",
	"Tiếng Việt",
	"Türkçe",
	"Ελληνικά",
	"Български",
	"Русский",
	"Українська",
	"עברית",
	"العربية",
	"हिन्दी",
	"বাংলা",
	"తెలుగు",
	"ภาษาไทย",
	"한국어",
	"日本語",
	"简体中文",
	"繁體中文"
]

countries = ["Afghanistan (افغانستان‎)",
"Aland Islands",
"Albania (Shqipëria)",
"Algeria (الجزائر‎)",
"American Samoa",
"Andorra",
"Angola",
"Anguilla",
"Antarctica",
"Antigua and Barbuda",
"Argentina",
"Armenia (Հայաստան)",
"Aruba",
"Australia",
"Austria (Österreich)",
"Azerbaijan (Azərbaycan)",
"Bahamas",
"Bahrain (البحرين‎)",
"Bangladesh (বাংলাদেশ)",
"Barbados",
"Belarus (Беларусь)",
"Belgium (België)",
"Belize",
"Benin (Bénin)",
"Bermuda",
"Bhutan (འབྲུག)",
"Bolivia, Plurinational State of",
"Bonaire, Sint Eustatius and Saba",
"Bosnia and Herzegovina (Босна и Херцеговина)",
"Botswana",
"Bouvet Island",
"Brazil (Brasil)",
"British Indian Ocean Territory",
"Brunei Darussalam",
"Bulgaria (България)",
"Burkina Faso",
"Burundi (Uburundi)",
"Cambodia (កម្ពុជា)",
"Cameroon (Cameroun)",
"Canada",
"Cape Verde (Kabu Verdi)",
"Cayman Islands",
"Central African Republic (République centrafricaine)",
"Chad (Tchad)",
"Chile",
"Christmas Island",
"Cocos (Keeling) Islands",
"Colombia",
"Comoros (جزر القمر‎)",
"Congo (Congo-Brazzaville)",
"Congo, the Democratic Republic of the (Jamhuri ya Kidemokrasia ya Kongo)",
"Cook Islands",
"Costa Rica",
"Cote d'Ivoire",
"Croatia (Hrvatska)",
"Cuba",
"Curacao",
"Cyprus (Κύπρος)",
"Czech Republic (Česká republika)",
"Denmark (Danmark)",
"Djibouti",
"Dominica",
"Dominican Republic (República Dominicana)",
"Ecuador",
"Egypt (مصر‎)",
"El Salvador",
"Equatorial Guinea (Guinea Ecuatorial)",
"Eritrea",
"Estonia (Eesti)",
"Ethiopia",
"Falkland Islands (Islas Malvinas)",
"Faroe Islands (Føroyar)",
"Fiji",
"Finland (Suomi)",
"France",
"French Guiana (Guyane française)",
"French Polynesia (Polynésie française)",
"French Southern Territories (Terres australes françaises)",
"Gabon",
"Gambia",
"Georgia (საქართველო)",
"Germany (Deutschland)",
"Ghana (Gaana)",
"Gibraltar",
"Greece (Ελλάδα)",
"Greenland (Kalaallit Nunaat)",
"Grenada",
"Guadeloupe",
"Guam",
"Guatemala",
"Guernsey",
"Guinea (Guinée)",
"Guinea-Bissau (Guiné Bissau)",
"Guyana",
"Haiti",
"Heard Island and McDonald Islands",
"Holy See (Vatican City State) (Città del Vaticano)",
"Honduras",
"Hong Kong (香港)",
"Hungary (Magyarország)",
"Iceland (Ísland)",
"India (भारत)",
"Indonesia",
"Iran, Islamic Republic of (ایران‎)",
"Iraq (العراق‎)",
"Ireland",
"Isle of Man",
"Israel (ישראל‎)",
"Italy (Italia)",
"Jamaica",
"Japan (日本)",
"Jersey",
"Jordan (الأردن‎)",
"Kazakhstan (Казахстан)",
"Kenya",
"Kiribati",
"Korea, Republic of (대한민국)",
"Kuwait (الكويت‎)",
"Kyrgyzstan",
"Lao People's Democratic Republic (ສ.ປ.ປ ລາວ)",
"Latvia (Latvija)",
"Lebanon (لبنان‎)",
"Lesotho",
"Liberia",
"Libya (ليبيا‎)",
"Liechtenstein",
"Lithuania (Lietuva)",
"Luxembourg",
"Macao (澳門)",
"Madagascar (Madagasikara)",
"Malawi",
"Malaysia",
"Maldives",
"Mali",
"Malta",
"Marshall Islands",
"Martinique",
"Mauritania (موريتانيا‎)",
"Mauritius (Moris)",
"Mayotte",
"Mexico (México)",
"Micronesia, Federated States of",
"Moldova, Republic of (Republica Moldova)",
"Monaco",
"Mongolia (Монгол)",
"Montenegro (Crna Gora)",
"Montserrat",
"Morocco (المغرب‎)",
"Mozambique (Moçambique)",
"Myanmar (မြန်မာ)",
"Namibia",
"Nauru",
"Nepal (नेपाल)",
"Netherlands (Nederland)",
"New Caledonia (Nouvelle-Calédonie)",
"New Zealand",
"Nicaragua",
"Niger (Nijar)",
"Nigeria",
"Niue",
"Norfolk Island",
"Northern Mariana Islands",
"Norway (Norge)",
"Oman (عُمان‎)",
"Pakistan (پاکستان‎)",
"Palau",
"Palestine, State of (فلسطين‎)",
"Panama (Panamá)",
"Papua New Guinea",
"Paraguay",
"Peru",
"Philippines",
"Pitcairn",
"Poland (Polska)",
"Portugal",
"Puerto Rico",
"Qatar (قطر‎)",
"Republic of North Macedonia (Македонија)",
"Reunion",
"Romania (România)",
"Russian Federation (Россия)",
"Rwanda",
"Saint Helena, Ascension and Tristan da Cunha",
"Saint Kitts and Nevis",
"Saint Lucia",
"Saint Martin [French part] (Saint-Martin [partie française])",
"Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)",
"Saint Vincent and the Grenadines",
"Samoa",
"San Marino",
"Sao Tome and Principe (São Tomé e Príncipe)",
"Saudi Arabia (المملكة العربية السعودية‎)",
"Senegal (Sénégal)",
"Serbia (Србија)",
"Seychelles",
"Sierra Leone",
"Singapore",
"Sint Maarten (Dutch part)",
"Slovakia (Slovensko)",
"Slovenia (Slovenija)",
"Solomon Islands",
"Somalia (Soomaaliya)",
"South Africa",
"South Georgia and the South Sandwich Islands",
"South Sudan (جنوب السودان‎)",
"Spain",
"Sri Lanka (ශ්‍රී ලංකාව))",
"St Barths (Saint-Barthélemy)",
"Sudan (السودان‎)",
"Suriname",
"Svalbard and Jan Mayen (Svalbard og Jan Mayen)",
"Swaziland",
"Sweden (Sverige)",
"Switzerland (Schweiz)",
"Syrian Arab Republic (سوريا‎)",
"Taiwan (台灣)",
"Tajikistan",
"Tanzania, United Republic of",
"Thailand (ไทย)",
"Timor-Leste",
"Togo",
"Tokelau",
"Tonga",
"Trinidad and Tobago",
"Tunisia (تونس‎)",
"Turkey (Türkiye)",
"Turkmenistan",
"Turks and Caicos Islands",
"Tuvalu",
"Uganda",
"Ukraine (Україна)",
"United Arab Emirates (الإمارات العربية المتحدة‎)",
"United Kingdom",
"United States",
"United States Minor Outlying Islands",
"Uruguay",
"Uzbekistan (Ўзбекистон)",
"Vanuatu",
"Venezuela, Bolivarian Republic of",
"Vietnam (Việt Nam)",
"Virgin Islands, British",
"Virgin Islands, U.S.",
"Wallis and Futuna",
"Western Sahara (الصحراء الغربية‎)",
"Yemen (اليمن‎)",
"Zambia",
"Zimbabwe"]


# pronouns = tuple([(pro) for pro in pronouns])
# countries = tuple([(c) for c in countries])
# language = tuple([(lan) for lan in languages])
